-
  branches:
    only:
      - master
  version: 1.0.{build}
  image: Visual Studio 2017
  build_script:
    - dotnet restore MarkdigEngine.sln
    - dotnet build MarkdigEngine.sln -c Release
    - cd MarkdigEngine.Tests
    - dotnet xunit
    - cd ..
    - ps: |
          if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
          {
            & dotnet pack -o ../artifacts -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION
            & nuget push artifacts/MarkdigEngine.$env:APPVEYOR_BUILD_VERSION.nupkg $env:mygetKey -Source $env:mygetMasterUrl
            & nuget push artifacts/MarkdigEngine.Extensions.$env:APPVEYOR_BUILD_VERSION.nupkg $env:mygetKey -Source $env:mygetMasterUrl
            
            & dotnet publish MarkdigEngine\MarkdigEngine.csproj -c Release -o publish
            & nuget pack Microsoft.DocAsCode.MarkdigEngine.nuspec -version $env:APPVEYOR_BUILD_VERSION -Prop Configuration=Release
            & nuget push ./Microsoft.DocAsCode.MarkdigEngine.$env:APPVEYOR_BUILD_VERSION.nupkg $env:mygetKey -Source $env:mygetMasterUrl
          }
  test: off

-
  branches:
    only:
      - dev
  version: 1.0.{build}
  image: Visual Studio 2017
  build_script:
    - dotnet restore MarkdigEngine.sln
    - dotnet build MarkdigEngine.sln -c Release
    - cd MarkdigEngine.Tests
    - dotnet xunit
    - cd ..
    - ps: |
          if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER)
          {
            & dotnet pack -o ../artifacts -c Release /p:Version=$env:APPVEYOR_BUILD_VERSION-alpha
            & nuget push artifacts/MarkdigEngine.$env:APPVEYOR_BUILD_VERSION-alpha.nupkg $env:mygetKey -Source $env:mygetDevUrl
            & nuget push artifacts/MarkdigEngine.Extensions.$env:APPVEYOR_BUILD_VERSION-alpha.nupkg $env:mygetKey -Source $env:mygetDevUrl

            & dotnet publish MarkdigEngine\MarkdigEngine.csproj -c Release -o publish
            & nuget pack Microsoft.DocAsCode.MarkdigEngine.nuspec -version $env:APPVEYOR_BUILD_VERSION-alpha -Prop Configuration=Release
            & nuget push ./Microsoft.DocAsCode.MarkdigEngine.$env:APPVEYOR_BUILD_VERSION-alpha.nupkg $env:mygetKey -Source $env:mygetDevUrl
          }
  test: off
  # on_finish:
  #   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
